spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/care
    username: postgres
    password : password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: susanbasnt123@gmail.com
    password: jkiw llhj xldd mnsq

    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

server:
  port: 1999
  servlet:
    context-path: /api


springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG

